add ticket 6 GET
Anna702/NC-NEWS-project pull request #5
Opened 2023-02-23 15:09 UTC by Anna702

2023-02-23 15:41 UTC, pippaamy commented on __tests__/app.test.js
> +        });
make sure the comments are sorted by created_at

2023-02-23 15:41 UTC, pippaamy commented on __tests__/app.test.js
> +      });
make a 200 test to test when it has a valid but has no comments responds with an empty array of comments

2023-02-23 15:43 UTC, pippaamy requested changes
Good work Anna, a few tests to add! Can you add these and then put in a new pull request?

2023-02-24 08:54 UTC, JVal-NC reviewed
Good work Anna, go ahead and merge

2023-02-24 08:55 UTC, merged